version: '3.2'
services:
    web:
        build: ./web
        ports:
            - "80:80"
            - "32000-32100:32000-32100"
        volumes:
            - /developpement/docker/docker_sf1_env/config/php.ini:/usr/local/etc/php/php.ini
            - /developpement/docker/docker_sf1_env/config/apache-custom.conf:/etc/apache2/conf-enabled/custom.conf
            - /developpement/docker/docker_sf1_env/config/vhost/:/etc/apache2/sites-enabled/
            - /developpement/sfProjects/sf1.4/:/var/www/html/
        links:
            - db
        environment:
            - ALLOW_OVERRIDE=All
    db:
        image: mysql:5.5.54
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql
              
volumes:
    mysql-data: